### ISSUE TITLE
Solving it on Windows 10

### ISSUE THREAD

**Issue by jamessong** [conda-forge/basemap-feedstock#41]
I solve it by adding the bellow code on the __init__.py under basemap folder (anaconda3\Lib\site-packages\mpl_toolkits\basemap\__init__.py)

First I imported the os and conda at the begging of __init__.py
import os, conda

at line #155, I changed the code:

```python
pyproj_datadir = os.environ['PROJ_LIB']
```
to:

```python
if 'PROJ_DIR' in os.environ:
    pyproj_datadir = os.environ['PROJ_DIR']
else:
    conda_file_dir = conda.__file__
    conda_dir = conda_file_dir.split('lib')[0]
    pyproj_datadir = os.path.join(os.path.join(os.path.join(os.path.join(conda_dir, 'lib'),
                                                            'site-packages'),'pyproj'),'data')
```

So, when I import Basemap, this code will check for the 'PROJ_LIB', if it is not there, it will set the 
pyproj_datadir to 'data' folder of pyproj.

Worked for me.
Regards

_Originally posted by @rpedruzzi in https://github.com/conda-forge/basemap-feedstock/issues/30#issuecomment-430702056_

**Comment by jamessong** [comment]
conda_file_dir = conda.__file__  

undefined name conda?

**Comment by ocefpaf** [comment]
You title is confusing. Solving what? The issue you refer to is solved by just using an updated conda BTW.

**Comment by jamessong** [comment]
> You title is confusing. Solving what? The issue you refer to is solved by just using an updated conda BTW.
Sorry, this is related to your answer to the question a while ago.  Could you be more specific? I have the newest version of anaconda, but the problem still exist. 


from mpl_toolkits.basemap import Basemap 
Traceback (most recent call last):

  File "<ipython-input-1-c18d700c1d76>", line 1, in <module>
    from mpl_toolkits.basemap import Basemap

  File "C:\ProgramData\Anaconda3\lib\site-packages\mpl_toolkits\basemap\__init__.py", line 146, in <module>
    pyproj_datadir = os.environ['PROJ_LIB']

  File "C:\ProgramData\Anaconda3\lib\os.py", line 678, in __getitem__
    raise KeyError(key) from None

KeyError: 'PROJ_LIB'

**Comment by ocefpaf** [comment]
Please post the `conda info` and `conda list` as is requested in the issue or we cannot debug it.
