### ISSUE TITLE
basemap 1.2.0 not working with proj4 6.0.0

### ISSUE THREAD

**Issue by xylar** [conda-forge/basemap-feedstock#45]
```
$ conda create -n basemap_test python=3.7 basemap
$ conda activate basemap_test
$ python -c "from mpl_toolkits.basemap import Basemap"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/xylar/miniconda3/envs/basemap_test/lib/python3.7/site-packages/mpl_toolkits/basemap/__init__.py", line 156, in <module>
    epsgf = open(os.path.join(pyproj_datadir,'epsg'))
FileNotFoundError: [Errno 2] No such file or directory: '/home/xylar/miniconda3/envs/basemap_test/share/proj/epsg'
```
This worked fine with proj4 5.2.0:
```
$ conda create -n basemap_test python=3.7 basemap proj4=5.2.0
$ conda activate basemap_test
$ python -c "from mpl_toolkits.basemap import Basemap"
```
It really does look like proj4 has deleted this directory.  Perhaps `basemap` needs to be fixed upstream but I figured I'd check here first to see if it's a recipe issue, particularly because another bug fix I put into `basemap` 4 months ago hasn't made it to release yet.

**Comment by ocefpaf** [comment]
It should be fixed now. Let me know if you find other packages that may have issues with `pyproj 6.0.0`.

**Comment by xylar** [comment]
Thank you, @ocefpaf! That'll do the trick.

**Comment by magdyabdel** [comment]
I still have this problem.
`conda create -n basemap_test python=3.7 basemap proj4=6.0.0 pandas pillow numpy
conda activate basemap_test
python -c "from mpl_toolkits.basemap import Basemap"`
Which returns following message.
`Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/magdy/anaconda3/envs/basemap_test/lib/python3.7/site-packages/mpl_toolkits/basemap/__init__.py", line 156, in <module>
    epsgf = open(os.path.join(pyproj_datadir,'epsg'))
FileNotFoundError: [Errno 2] No such file or directory: '/home/magdy/anaconda3/envs/basemap_test/share/proj/epsg'`

**Comment by ocefpaf** [comment]
@magdyabdel you cannot install `basemap` with `proj4 6` b/c `basemap` is not compatible with it. In https://github.com/conda-forge/basemap-feedstock/pull/46 I only pinned the `pyproj` version that uses `proj4 5.x`.  You probably got a package with bad metadata. I'll remove that one from the channel.

**Comment by ocefpaf** [comment]
Also, can you send a `conda list` of your env? I could find a package with the bad metadata and I'm guessing you may be mixing deafults and conda-forge there.

**Comment by magdyabdel** [comment]
Thank you for the fast response @ocefpaf ! Yeah, I'm new to all of this.
```
  basemap            pkgs/main/linux-64::basemap-1.2.0-py37h705c2d8_0
  bzip2              conda-forge/linux-64::bzip2-1.0.6-h14c3975_1002
  ca-certificates    conda-forge/linux-64::ca-certificates-2019.3.9-hecc5488_0
  certifi            conda-forge/linux-64::certifi-2019.3.9-py37_0
  cycler             conda-forge/noarch::cycler-0.10.0-py_1
  dbus               conda-forge/linux-64::dbus-1.13.6-he372182_0
  expat              conda-forge/linux-64::expat-2.2.5-hf484d3e_1002
  fontconfig         conda-forge/linux-64::fontconfig-2.13.1-he4413a7_1000
  freetype           conda-forge/linux-64::freetype-2.10.0-he983fc9_0
  geos               conda-forge/linux-64::geos-3.6.2-hfc679d8_4
  gettext            conda-forge/linux-64::gettext-0.19.8.1-hc5be6a0_1002
  glib               conda-forge/linux-64::glib-2.58.3-hf63aee3_1001
  gst-plugins-base   conda-forge/linux-64::gst-plugins-base-1.14.4-hdf3bae2_1001
  gstreamer          conda-forge/linux-64::gstreamer-1.14.4-h66beb1c_1001
  icu                conda-forge/linux-64::icu-58.2-hf484d3e_1000
  jpeg               conda-forge/linux-64::jpeg-9c-h14c3975_1001
  kiwisolver         conda-forge/linux-64::kiwisolver-1.1.0-py37hc9558a2_0
  libblas            conda-forge/linux-64::libblas-3.8.0-10_openblas
  libcblas           conda-forge/linux-64::libcblas-3.8.0-10_openblas
  libffi             conda-forge/linux-64::libffi-3.2.1-he1b5a44_1006
  libgcc-ng          pkgs/main/linux-64::libgcc-ng-8.2.0-hdf63c60_1
  libgfortran-ng     pkgs/main/linux-64::libgfortran-ng-7.3.0-hdf63c60_0
  libiconv           conda-forge/linux-64::libiconv-1.15-h516909a_1005
  liblapack          conda-forge/linux-64::liblapack-3.8.0-10_openblas
  libpng             conda-forge/linux-64::libpng-1.6.37-hed695b0_0
  libstdcxx-ng       pkgs/main/linux-64::libstdcxx-ng-8.2.0-hdf63c60_1
  libtiff            conda-forge/linux-64::libtiff-4.0.10-h648cc4a_1001
  libuuid            conda-forge/linux-64::libuuid-2.32.1-h14c3975_1000
  libxcb             conda-forge/linux-64::libxcb-1.13-h14c3975_1002
  libxml2            conda-forge/linux-64::libxml2-2.9.9-h13577e0_0
  matplotlib         conda-forge/linux-64::matplotlib-3.1.0-py37_1
  matplotlib-base    conda-forge/linux-64::matplotlib-base-3.1.0-py37hfd891ef_1
  ncurses            conda-forge/linux-64::ncurses-6.1-hf484d3e_1002
  numpy              conda-forge/linux-64::numpy-1.16.3-py37he5ce36f_0
  olefile            conda-forge/noarch::olefile-0.46-py_0
  openblas           conda-forge/linux-64::openblas-0.3.6-h6e990d7_2
  openssl            conda-forge/linux-64::openssl-1.1.1b-h14c3975_1
  pandas             conda-forge/linux-64::pandas-0.24.2-py37hb3f55d8_0
  pcre               conda-forge/linux-64::pcre-8.41-hf484d3e_1003
  pillow             conda-forge/linux-64::pillow-6.0.0-py37he7afcd5_0
  pip                conda-forge/linux-64::pip-19.1-py37_0
  proj4              conda-forge/linux-64::proj4-6.0.0-he751ad9_1
  pthread-stubs      conda-forge/linux-64::pthread-stubs-0.4-h14c3975_1001
  pyparsing          conda-forge/noarch::pyparsing-2.4.0-py_0
  pyproj             conda-forge/linux-64::pyproj-2.1.3-py37h7bc548f_1
  pyqt               conda-forge/linux-64::pyqt-5.9.2-py37hcca6a23_0
  pyshp              conda-forge/noarch::pyshp-2.1.0-py_0
  python             conda-forge/linux-64::python-3.7.3-h5b0a415_0
  python-dateutil    conda-forge/noarch::python-dateutil-2.8.0-py_0
  pytz               conda-forge/noarch::pytz-2019.1-py_0
  qt                 conda-forge/linux-64::qt-5.9.7-h52cfd70_2
  readline           conda-forge/linux-64::readline-7.0-hf8c457e_1001
  setuptools         conda-forge/linux-64::setuptools-41.0.1-py37_0
  sip                conda-forge/linux-64::sip-4.19.8-py37hf484d3e_1000
  six                conda-forge/linux-64::six-1.12.0-py37_1000
  sqlite             conda-forge/linux-64::sqlite-3.28.0-h8b20d00_0
  tk                 conda-forge/linux-64::tk-8.6.9-h84994c4_1001
  tornado            conda-forge/linux-64::tornado-6.0.2-py37h516909a_0
  wheel              conda-forge/linux-64::wheel-0.33.4-py37_0
  xorg-libxau        conda-forge/linux-64::xorg-libxau-1.0.9-h14c3975_0
  xorg-libxdmcp      conda-forge/linux-64::xorg-libxdmcp-1.1.3-h516909a_0
  xz                 conda-forge/linux-64::xz-5.2.4-h14c3975_1001
  zlib               conda-forge/linux-64::zlib-1.2.11-h14c3975_1004
```

**Comment by ocefpaf** [comment]
As I suspect you are getting basemap from `defaults` (pkgs/main) and `proj4` from `conda-forge`.  If you [enable `strict`](https://conda-forge.org/docs/user/tipsandtricks.html#how-to-fix-it) with `conda-forge` as your primary channel you will get an error when trying to install `basemap` with `proj4 6`, as expected, instead of a broken environment.

**Comment by magdyabdel** [comment]
Thank you for clarifying. I appreciate the effort.
